### ISSUE TITLE
LISTMap Tile service

### ISSUE THREAD

**Issue by tastrax** [nextgis/quickmapservices_contrib#27]
I am trying to add a custom tile service into quickmaps - works via WMTS but not in QMS - any ideas. I generally get a timeout (in QMS) but not WMTS?

[general]
id = list_topo
type = TMS

[ui]
group = australia
alias = TAS LIST Topo
icon = list_topo.PNG

[license]
name = LIST Tasmania
link = https://creativecommons.org/licenses/by/3.0/au/
copyright_text = Â©State of Tasmania
copyright_link = http://listdata.thelist.tas.gov.au/public/LandTasmaniaDataAttributionGuidelines.pdf
terms_of_use = http://listdata.thelist.tas.gov.au/public/LISTWebServicesTermsConditions.pdf

[tms]
url = http://services.thelist.tas.gov.au/arcgis/rest/services/Basemaps/Topographic/ImageServer/tile/{z}/{y}/{x}.png
zmin = 1
zmax = 18
y_origin_top = 0

**Comment by yellow-sky** [comment]
Try to use this url:
http://services.thelist.tas.gov.au/arcgis/rest/services/Basemaps/Topographic/MapServer/tile/{z}/{y}/{x}
and set:
y_origin_top = 1

**Comment by tastrax** [comment]
given I am not familiar with github could the attached be added to the groups and data sources?

**Comment by simgislab** [comment]
@tastrax Hi, you have a unique opportunity to be the first to try our brand new way to add your services to QMS without special knowledge (github etc).

1. Login here: https://qms.nextgis.com
2. Add services you need
3. Enjoy results in QGIS and other software that supports QMS

Let us know if you encounter problems (this is early beta) or need any clarifications.

**Comment by tastrax** [comment]
Many thanks Maxim,

How can I add a new group via the interface? I am keen to have Australia as a menu item with links to states mapping services underneath.

**Comment by simgislab** [comment]
new service doesn't have groups yet, but we're working on it. We believe this is the way to go for QMS as number of services is growing and tree-view is limiting.

You'll need to decide:
1. Easy to add, easy to find, plain list - no groups yet (probably later).
2. Harder to add, tree list - groups

**Comment by tastrax** [comment]
Its certainly very easy to add new entries. I assume these get into the contributed pack for the QGIS plugin eventually?

**Comment by simgislab** [comment]
It's better! It's already available through QGIS.

![](http://m-d.me/img/ss/20161125-8v1-212kb.jpg)

**Comment by tastrax** [comment]
Ah, now I get it. I thought it would be in the menu items!

Many thanks

**Comment by simgislab** [comment]
it is great to see our service in use. Thanks!
I'm closing this issue for now.
Please let us know if there is anything we can help with!
