### ISSUE TITLE
Get Contributed Pack - Not Working - Mac

### ISSUE THREAD

**Issue by taylorulien** [nextgis/quickmapservices_contrib#44]
When I'm trying to add additional services to to the QuickMapServices on my Macbook, it comes up with an error:

> Error on getting contrib pack: <type 'exceptions.Exception'> 6

And doesn't add any additional services.

**Comment by linmish** [comment]
Hi Taylor, 
Did you find a solution to this problem ? I have the same one and would be interested in knowing how you resolved it. Thanks !

**Comment by simgislab** [comment]
https://github.com/nextgis/quickmapservices
