### ISSUE TITLE
https instead of http

### ISSUE THREAD

**Issue by riccardoklinger** [nextgis/quickmapservices_contrib#47]
I would love to use https instead of http. could you change this, please?

**Comment by simgislab** [comment]
for particular service? send pull request

but better user qms.nextgis.com, contrib package is very outdated

**Comment by riccardoklinger** [comment]
unfortunately I see same non secure URLS in qms.nextgis.com

**Comment by simgislab** [comment]
well, you can create new secure ones, this is the point of QMS catalog
