### ISSUE TITLE
Tianditu support was broken due to server API changes

### ISSUE THREAD

**Issue by liuqun** [nextgis/quickmapservices_contrib#52]
Since year 2020 or later, the Chinese governmental TMS server (aka Tianditu) had changed its public access policy.
Their new TMS API now requires a non-standard parameter `tk` as the application token:

The official announcement from Tianditu official web site:
- http://lbs.tianditu.gov.cn/server/MapService.html

Releated issue：
- https://github.com/nextgis/quickmapservices_contrib/pull/38

**Comment by simgislab** [comment]
Tianditu  removed
