### ISSUE TITLE
росреестр базовый слой и подписи отмывка рельефа

### ISSUE THREAD

**Issue by Sowa1980** [nextgis/quickmapservices_contrib#54]
Исправьте ссылку на 
1. базовый слой
https://pkk.rosreestr.ru/arcgis/rest/services/BaseMaps/BaseMap/MapServer
2. подписи
https://pkk.rosreestr.ru/arcgis/rest/services/BaseMaps/Anno/MapServer
3.  отмывка рельефа
https://services.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer

Остальные тоже надо исправить неработают

**Comment by simgislab** [comment]
неработающие сервисы удалены

если вы хотите что-то исправить, то необходимо исправить это самостоятельно, прислав соответствующие PR, других вариантов нет
