### ISSUE TITLE
QGIS Error on getting contrib pack: 203 (QMS settings > get contributed pack)

### ISSUE THREAD

**Issue by GITHUBAntoineDENIS** [nextgis/quickmapservices_contrib#55]
Hi,
In QGIS (3.16.16 or 3.22) when we try to "get contributed pack" in the QMS settings, we get an error message "error on getting contrib pack: 203". Confer image.

![a 530](https://user-images.githubusercontent.com/44610746/158331158-22b50fb5-86a9-4f9b-b49e-116354ede64e.PNG)

It would be nice to be solved.
Best regards,
Antoine DENIS

**Comment by simgislab** [comment]
https://github.com/nextgis/quickmapservices
