### ISSUE TITLE
Get Contributed Pack button gives me Error

### ISSUE THREAD

**Issue by asgharibraheembaloch** [nextgis/quickmapservices_contrib#56]
On Pressing Get Contributed Pack button gives me Error
![image](https://user-images.githubusercontent.com/46741864/158349570-05e8e7f1-c817-42b2-873a-b42a3778539f.png)

**Comment by LuiCotias** [comment]
I'm having the same issue.

**Comment by Mythvens** [comment]
I have the similar issue, too. 
Error on getting contrib pack: 3

**Comment by Carolinah23** [comment]
I have the same error (Error on getting contrib pack:203). I have QGIS 3.24 Tisler and my OS is Ubuntu 20.04, I used to have 3.20 but Ubuntu updated it, and since I would not be able to use QuickMapServices.

**Comment by simgislab** [comment]
please try again

if problem persists, check if your network is behind proxy which you've not set up in QGIS

**Comment by simgislab** [comment]
please read this for more info
https://github.com/nextgis/quickmapservices/issues/239
