### ISSUE TITLE
Yandex online-maps are not displayed

### ISSUE THREAD

**Issue by AnnaBorisenko13** [nextgis/quickmapservices_contrib#58]
dear developers, during proceeding with online maps in QGIS, few weeks ago we realized that Yandex online maps didn't displayed any more.

Steps to reproduce the issue
As I know, Yandex stopped data exchange via the http protocol.
Now only https protocol works. Please change source descriptions for Yandex maps on page https://github.com/nextgis/quickmapservices_contrib/commit/91c920d1ee5f25b6ade003be1832cd0cfa4c6336
Thank you for your job!

I have wrote before in issue https://github.com/qgis/QGIS/issues/51275 but developers redirected me here.

**Comment by simgislab** [comment]
please watch video here: https://qms.nextgis.com/about

if you need code changes - please send pull request for review
