### ISSUE TITLE
Added here wego and mapbox satellite

### ISSUE THREAD

**Issue by jo-chemla** [nextgis/quickmapservices_contrib#60]
Would be nice to add more options to the contributed pack, like these two which were recently contributed to [NextGis QMS](https://qms.nextgis.com/)

[Here Wego Satellite](https://qms.nextgis.com/geoservices/6087/)
[Mapbox - Satellite](https://qms.nextgis.com/geoservices/6088/)

Note: cross posted originally on [the plugin repo](https://github.com/nextgis/quickmapservices/issues/245)

**Comment by simgislab** [comment]
Are you ok with sharing your API key with the world?

**Comment by jo-chemla** [comment]
I don't remember exactly where, but these were API keys/tokens I retrieved from the official here and mapbox API docs or satellite tiles demos a few years back. They have been working flawlessly since, but might indeed need to be updated from time to time. 

Note some other service providers do offer map view via their public api tokens, but this should probably be left up to the user to enter their own api keys - probably via the `Edit My Features` of the QMS qgis plugin. 

PS: these edits led me to test out the `Search QMS` and `Add My Services`, these are also great utilities within the qgis plugin!

**Comment by jo-chemla** [comment]
Note this is using the old `app_id/app_code` for here instead of the new `apiKey`. And I can if needed update the here and mapbox tokens to the new one each use on their docs - not sure if/how often each rotate these public api tokens though.

**Comment by simgislab** [comment]
added

**Comment by jo-chemla** [comment]
Thanks!
Note mapbox is not yet on qms.nextgis.com, probably because webp tiles are not considered valid images as shown here https://github.com/nextgis/quickmapservices_contrib/pull/61#issuecomment-1825250586

**Comment by jo-chemla** [comment]
Hi there, did you have time to enable webp tile sources within NextGIS QMS? Source loads on your leaflet map canvas, but cannot be made public with error `Service is failing validation and can't be made public. Edit it to fix errors or let us know.` + errors comes with text `service response is not image`.

https://qms.nextgis.com/geoservices/6088/

![image](https://github.com/nextgis/quickmapservices_contrib/assets/16822841/10dad8d3-af67-4442-a424-902daf0c5680)

**Comment by jo-chemla** [comment]
Opening a new issue for the webp tiles integration here https://github.com/nextgis/quickmapservices_contrib/issues/64
