### ISSUE TITLE
Kosmosnimki API-key is inactive

### ISSUE THREAD

**Issue by simgislab** [nextgis/quickmapservices_contrib#7]
> url = http://maps.kosmosnimki.ru/TileService.ashx?Request=gettile&LayerName=E50931C3B2DD4E0FA2C03366552EEAA1&apikey=L5VW1QBBHJ&crs=epsg:3857&z={z}&x={x}&y={y}
> 
> <Exception><Message>Internal error: APIkey not active</Message></Exception>

**Comment by blackgis** [comment]
this apikey works: U96GP973UH but not for overlay layer

**Comment by simgislab** [comment]
kosmosnimki services removed
