### ISSUE TITLE
natural earth

### ISSUE THREAD

**Issue by dschneiderch** [nextgis/quickmapservices_contrib#9]
I would love to see Natural Earth data (http://www.naturalearthdata.com/) available through your plugin, which is a great feature addition already. keep up the good work.

**Comment by simgislab** [comment]
we invite people to add services themselves, this is quite easy, just fork and create a copy and then edit and create pull request against this repository.
https://github.com/nextgis/quickmapservices/wiki/Adding-data-source

Thanks.

**Comment by simgislab** [comment]
it seems like there is WMS/TMS service for Natural Earth data

@trolleway let's add those to data.nextgis.com and feed back into QMS

**Comment by trolleway** [comment]
Blocked, need to update gdal at our server data.nextgis.com

**Comment by simgislab** [comment]
qms.nextgis.com
